##fluxo de trabalho para acrescentar  regra
##workflow:
  ##regra que se for diferente da branch main nunca fazer e caso contrário fazer
  ##rules:
  ## essa é uma variável global da branch em uso, != é se for diferente
    ##- if: $CI_COMMIT_BRANCH != "main"
      ##when: never
    ##- when: always

##especificando antes diz que será utilizado em todos os jobs
##image: docker pull node:19.4

##criar estágios
stages:
  - teste
  - build
  - deploy

##job
executar_teste:
##chamando o stage no script
  stage: teste
  before_script:
    ##preparação a ser feita como definição de variáveis, especificação de chaves de acesso etc
    - echo "Preparando testes"
    ##./ para dizer que está no mesmo diretório
    - chmod +x ./script.sh
  ##atributo obrigatório
  script:
    ./script.sh

  after_script:
    ##limpeza de arquivos temporários etc pode ser executado com o after
    - echo "Apagando arquivos temporários..."

executar_teste2:
## define uma imagem especifica para o job
  image: node:19.4
  stage: teste
  script:
    - echo "Executando teste 2..."
    ##mostrar versão do npm
    - npm version

criar_imagens:
  ##only:
    ##- main
  stage: build
  script:
    - echo "Criando as imagens..." 

push_imagens:
## especifíca em somente em qual branch vai rodar
  ##only:
    ##- main
##só executa se a anterior concluiu com sucesso
  needs: 
    ## especifica quais são as dependencias que devem ter sido concluídas
    - criar_imagens
  stage: build
  script:
    - echo "Realizando upload das imagens..."

kubernetes:
  needs:
    - push_imagens
  ##only:
    ##- main
  stage: deploy
  script:
    - echo "Executando deploy..."